name: test

on:
  repository_dispatch:
  workflow_dispatch:
#    inputs:
#      ssh:
#        description: 'SSH connection to Actions'
#        required: false
#        default: 'false'
#周日22时 CN周一6时
  crontab: 0 22 * * 0 environmentalists .SERVERCHAN_SCKEY == 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config/R4S.config
  DIY_P1_SH: diy_script/diy-part_R4S1.sh
  DIY_P2_SH: diy_script/diy-part_R4S2.sh
  COMMIT_LOG_NUM: 1
  RELEASE_TAG: R4S
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  SERVERCHAN_SCKEY: true 
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: PUSHPLUS信息通知
      if: env.SERVERCHAN_SCKEY == 'true'
      run: |
        curl -k --data chat_id=${{ secrets.TGI }} --data "text=Have a good journey, Mr. Weyland." "https://api.telegram.org/bot${{ secrets.TG_TOKE }}/schedule:
   
    - name: PUSHPLUS信息通知
      if: env.SERVERCHAN_SCKEY == 'true'
      run: |
        curl -k --data token="${{ secrets.PUSH_PLUS_TOK }}" --data title="开始编译$RELEASE_TAG-$(date +"%Y.%m.%d-%H%M")" --data "content=🎉 主人：您正在使用R4S文件夹编译固件中号),请耐心等待...... 😋💐" "http://www.pushplus.plus/send"
